export type LevelKey = "beginner" | "intermediate" | "advanced";
export type Speaker = string;
export type PracticeLine = { id: string; speaker: Speaker; text: string; translation: string; note: string };
export type ListeningLine = PracticeLine;
export type SceneKey = "greetings" | "travel" | "business" | "housing" | "medical" | "banking" | "shopping" | "transit" | "government" | "school";

export const LEVELS = [
  { key: "beginner" as const, title: "初级", subtitle: "Beginner" },
  { key: "intermediate" as const, title: "中级", subtitle: "Intermediate" },
  { key: "advanced" as const, title: "高级", subtitle: "Advanced" },
];

export const SCENES = [
  { key: "greetings", title: "日常问候", subtitle: "打招呼与寒暄" },
  { key: "travel", title: "旅游出行", subtitle: "机场、酒店与问路" },
  { key: "business", title: "商务交流", subtitle: "会议、协作与表达" },
  { key: "housing", title: "租房居住", subtitle: "看房、签租约与报修" },
  { key: "medical", title: "就医看诊", subtitle: "预约、看病与买药" },
  { key: "banking", title: "银行开户", subtitle: "开卡、存取与转账" },
  { key: "shopping", title: "购物用餐", subtitle: "超市、点餐与退换" },
  { key: "transit", title: "交通通勤", subtitle: "公交、地铁与驾照" },
  { key: "government", title: "政务办理", subtitle: "证件、邮局与税务" },
  { key: "school", title: "学校沟通", subtitle: "入学、家校与请假" },
] as const;

export const SCENE_CONTENT: Record<SceneKey, ListeningLine[]> = {
  greetings: [
    { id: "greetings-1", speaker: "Alex", text: "Good morning! Did you sleep well last night?", translation: "早上好！昨晚睡得好吗？", note: "用 'sleep well' 询问对方睡眠质量，是日常问候的温馨开场。" },
    { id: "greetings-2", speaker: "Mia", text: "Morning, Alex! Yes, I did, though I stayed up a bit late reading.", translation: "早啊，亚历克斯！是的，睡得不错，不过我读书稍微熬夜了一会儿。", note: "用 'stayed up a bit late' 表达熬夜，语气自然。" },
    { id: "greetings-3", speaker: "Alex", text: "What kind of book were you reading? Anything interesting?", translation: "你在读什么书？有什么有意思的内容吗？", note: "用 'What kind of book' 询问书籍类别，开启共同话题。" },
    { id: "greetings-4", speaker: "Mia", text: "It's a novel about modern art history. Quite fascinating actually.", translation: "是一本关于现代艺术史的小说。其实挺引人入胜的。", note: "实用短语 'Quite fascinating' 增强赞叹的语气。" },
    { id: "greetings-5", speaker: "Alex", text: "I've always found art history inspiring. Do you visit galleries often?", translation: "我一直觉得艺术史很启发灵感。你经常去参观画廊吗？", note: "用 'inspiring' 表达对艺术的启发感。" },
    { id: "greetings-6", speaker: "Mia", text: "Whenever I have a free weekend, I try to check out a new exhibition.", translation: "每逢周末有空，我都尽量去看看新的展览。", note: "用 'Whenever' 表示每当……的时候，表达习惯。" },
    { id: "greetings-7", speaker: "Alex", text: "That sounds like a wonderful habit. By the way, are you heading to work now?", translation: "听起来是个很棒的习惯。对了，你现在正要去上班吗？", note: "用 'By the way' 转换话题过渡到当前行程。" },
    { id: "greetings-8", speaker: "Mia", text: "Yes, taking the subway. It's usually quite busy at this hour.", translation: "对，坐地铁去。这个点人通常挺多的。", note: "用 'quite busy' 形容早高峰拥挤。" },
    { id: "greetings-9", speaker: "Alex", text: "True. Have you had your breakfast yet, or are you grabbing coffee on the way?", translation: "确实。你吃过早餐了吗，还是在路上买咖啡？", note: "用 'grabbing coffee' 表达顺便买咖啡。" },
    { id: "greetings-10", speaker: "Mia", text: "I grabbed a quick pastry and a latte near the station.", translation: "我在车站附近匆忙买了个糕点和拿铁。", note: "用 'grabbed a quick' 形容快捷简便的饮食。" },
    { id: "greetings-11", speaker: "Alex", text: "That works. What are your main tasks scheduled for today?", translation: "那挺好。你今天安排的主要工作任务是什么？", note: "用 'scheduled for today' 询问日程安排。" },
    { id: "greetings-12", speaker: "Mia", text: "I need to finalize a quarterly design report and review team feedback.", translation: "我需要完成一份季度设计报告并审核团队反馈。", note: "用 'finalize' 表示最后定稿。" },
    { id: "greetings-13", speaker: "Alex", text: "Sounds like a productive morning ahead. Good luck with that!", translation: "听起来上午会很充实。祝你一切顺利！", note: "罗列祝愿的常用表达 'Good luck with that!'。" },
    { id: "greetings-14", speaker: "Mia", text: "Thanks, Alex! What about your schedule? Working remotely today?", translation: "谢谢，亚历克斯！你今天日程呢？今天在家远程办公吗？", note: "用 'Working remotely' 询问是否居家办公。" },
    { id: "greetings-15", speaker: "Alex", text: "No, I'm at the office today. We have a brainstorming session this afternoon.", translation: "不，我今天在办公室。我们下午有一场头脑风暴会。", note: "用 'brainstorming session' 表达头脑风暴会议。" },
    { id: "greetings-16", speaker: "Mia", text: "Ah, team collaboration is always energetic. Hope you get great ideas.", translation: "啊，团队协作总是充满活力。希望你们能碰撞出棒的点子。", note: "用 'energetic' 形容充满活力的团队氛围。" },
    { id: "greetings-17", speaker: "Alex", text: "We certainly hope so. Oh, look at the weather outside, looks like rain.", translation: "我们当然希望如此。哦，你看外面的天气，好像要下雨了。", note: "用 'looks like rain' 预测天气。" },
    { id: "greetings-18", speaker: "Mia", text: "Good thing I packed my umbrella in the bag this morning.", translation: "幸亏我今天早上在包里带了雨伞。", note: "用 'Good thing' 表示幸亏、好在。" },
    { id: "greetings-19", speaker: "Alex", text: "That's foresight! Always be prepared for unexpected showers.", translation: "真有远见！对突如其来的阵雨总得有准备。", note: "用 'foresight' 表示有远见。" },
    { id: "greetings-20", speaker: "Mia", text: "Definitely. Well, my stop is coming up soon. Have a great day!", translation: "确实。嗯，我的站快到了。祝你今天过得愉快！", note: "用 'stop is coming up' 表示即将到站。" },
    { id: "greetings-21", speaker: "Alex", text: "You too, Mia! Enjoy your workday and stay dry.", translation: "你也是，米娅！工作愉快，注意别淋湿了。", note: "用 'stay dry' 表达雨天温馨问候。" },
    { id: "greetings-22", speaker: "Mia", text: "Will do. Catch you later online or this weekend.", translation: "好的，回头网上或者周末再联系。", note: "用 'Will do' 简洁应答。" },
    { id: "greetings-23", speaker: "Alex", text: "Sounds like a plan. Goodbye!", translation: "就这么定啦。再见！", note: "用 'Sounds like a plan' 表示赞同安排。" },
    { id: "greetings-24", speaker: "Mia", text: "Bye-bye, Alex!", translation: "拜拜，亚历克斯！", note: "日常道别。" },
    { id: "greetings-25", speaker: "Alex", text: "By the way, did you try that new bakery downtown yesterday?", translation: "对了，你昨天尝过市中心那家新开的面包店了吗？", note: "用 'By the way' 进一步深入闲聊。" },
    { id: "greetings-26", speaker: "Mia", text: "Yes, I did! Their cinnamon rolls are absolute perfection.", translation: "尝过了！他们的肉桂卷简直完美。", note: "用 'absolute perfection' 形容极致美味。" },
    { id: "greetings-27", speaker: "Alex", text: "I must go there this Saturday morning then.", translation: "那这周六早上我一定得去一趟。", note: "用 'I must go' 表达强烈的兴趣。" },
    { id: "greetings-28", speaker: "Mia", text: "You won't regret it. Just make sure to arrive early before lines form.", translation: "你不会后悔的。记得趁早去，免得排长队。", note: "用 'You won't regret it' 给出推荐保证。" },
    { id: "greetings-29", speaker: "Alex", text: "Got it. Early bird gets the delicious pastry.", translation: "明白了。早起的鸟儿有甜点吃。", note: "引用经典谚语。" },
    { id: "greetings-30", speaker: "Mia", text: "Haha, exactly right. Enjoy your coffee!", translation: "哈哈，完全正确。好好享用咖啡吧！", note: "愉快收尾。" },
    { id: "greetings-31", speaker: "Alex", text: "Thanks again, Mia. See you around.", translation: "再次谢谢你，米娅。回头见。", note: "日常寒暄。" },
    { id: "greetings-32", speaker: "Mia", text: "Take care, Alex.", translation: "保重，亚历克斯。", note: "温和回应。" },
    { id: "greetings-33", speaker: "Alex", text: "Cheers to a lovely week ahead.", translation: "预祝接下来一周心情美妙。", note: "用 'Cheers to' 表达美好祝愿。" },
    { id: "greetings-34", speaker: "Mia", text: "Cheers! Have a wonderful day.", translation: "干杯！祝你有美好的一天。", note: "回以祝福。" },
    { id: "greetings-35", speaker: "Alex", text: "See you!", translation: "再见！", note: "简短道别。" },
    { id: "greetings-36", speaker: "Mia", text: "See you!", translation: "再见！", note: "呼应告别。" },
    { id: "greetings-37", speaker: "Alex", text: "Remember to stay hydrated today.", translation: "今天记得多喝水补水哦。", note: "健康提醒。" },
    { id: "greetings-38", speaker: "Mia", text: "I will, thanks for reminding.", translation: "我会的，谢谢提醒。", note: "感谢关心。" },
    { id: "greetings-39", speaker: "Alex", text: "No problem at all. Bye!", translation: "不用客气。再见！", note: "道别收尾。" },
    { id: "greetings-40", speaker: "Mia", text: "Goodbye!", translation: "再见！", note: "最终告别。" },
  ],
  travel: [
    { id: "travel-1", speaker: "Traveler", text: "Excuse me, could you direct me to the international departures terminal?", translation: "打扰一下，请问去国际出发航站楼怎么走？", note: "用 'could you direct me to' 礼貌询问路线。" },
    { id: "travel-2", speaker: "Agent", text: "Certainly. Head straight down this corridor, then take the escalator to level two.", translation: "当然可以。顺着这条走廊一直往前走，然后乘自动扶梯到二楼。", note: "用 'Head straight down' 指示直行方向。" },
    { id: "travel-3", speaker: "Traveler", text: "Is there a currency exchange desk near the security checkpoint?", translation: "安检处附近有货币兑换处吗？", note: "用 'near the security checkpoint' 限定地点。" },
    { id: "travel-4", speaker: "Agent", text: "Yes, right next to Gate 12. They offer competitive exchange rates.", translation: "有的，就在12号登机口旁边。他们的汇率挺划算的。", note: "用 'competitive exchange rates' 表达汇率优惠。" },
    { id: "travel-5", speaker: "Traveler", text: "Great. Do I need to fill out any customs declaration forms beforehand?", translation: "太好了。我需要提前填写海关申报单吗？", note: "用 'customs declaration forms' 询问海关手续。" },
    { id: "travel-6", speaker: "Agent", text: "Only if you are carrying goods exceeding the duty-free allowance.", translation: "只有当你携带的物品超过免税额度时才需要。", note: "用 'duty-free allowance' 表示免税额度。" },
    { id: "travel-7", speaker: "Traveler", text: "I have only personal belongings and souvenirs, so I should be fine.", translation: "我只有个人随身物品和纪念品，应该没问题。", note: "用 'personal belongings' 表示随身行李。" },
    { id: "travel-8", speaker: "Agent", text: "That sounds straightforward. Have your passport and boarding pass ready.", translation: "那很简单。请准备好您的护照和登机牌。", note: "用 'Have your... ready' 提示提前备好证件。" },
    { id: "travel-9", speaker: "Traveler", text: "Here they are. My flight leaves at 2:30 PM, right?", translation: "都在这儿了。我的航班是下午2点半起飞，对吧？", note: "用陈述句加反问确认起飞时间。" },
    { id: "travel-10", speaker: "Agent", text: "Let me check... Yes, flight UA882 to London. Boarding begins at 1:45 PM.", translation: "让我查一下……对，去伦敦的UA882航班。1点45分开始登机。", note: "用 'Let me check' 现场核对航班信息。" },
    { id: "travel-11", speaker: "Traveler", text: "Which gate will the boarding be conducted from?", translation: "将在哪个登机口登机？", note: "用 'Which gate' 询问登机口。" },
    { id: "travel-12", speaker: "Agent", text: "Gate B22, located at the far end of this concourse.", translation: "B22登机口，位于这条候机大厅的尽头。", note: "用 'far end of this concourse' 指明具体方位。" },
    { id: "travel-13", speaker: "Traveler", text: "Thank you for the precise information. Are there any delays reported?", translation: "感谢您提供准确的信息。目前有报告任何延误吗？", note: "用 'precise information' 表示感谢。" },
    { id: "travel-14", speaker: "Agent", text: "No delays at the moment. Weather conditions along the route are clear.", translation: "目前没有延误。沿途天气状况良好。", note: "用 'weather conditions' 说明天气正常。" },
    { id: "travel-15", speaker: "Traveler", text: "That's a relief. Can I bring my guitar as carry-on luggage?", translation: "那我就放心了。我的吉他可以作为随身行李带上飞机吗？", note: "用 'carry-on luggage' 表示随身行李。" },
    { id: "travel-16", speaker: "Agent", text: "As long as it fits in the overhead bin or under the seat in front of you.", translation: "只要它能放进头顶行李舱或你前方的座椅底下就可以。", note: "用 'overhead bin' 表示头顶行李舱。" },
    { id: "travel-17", speaker: "Traveler", text: "I measured it beforehand, so it complies with dimension limits.", translation: "我提前量过尺寸，符合规定的大小限制。", note: "用 'complies with dimension limits' 说明符合尺寸。" },
    { id: "travel-18", speaker: "Agent", text: "Wonderful. You'll also need a luggage tag for gate check if space is tight.", translation: "太好了。如果客舱空间紧张，登机口可能需要加挂行李签。", note: "用 'gate check' 表示登机口托运。" },
    { id: "travel-19", speaker: "Traveler", text: "Understood. Where is the nearest lounge for frequent flyers?", translation: "明白了。最近的常旅客休息室在哪里？", note: "用 'frequent flyers' 表示常旅客。" },
    { id: "travel-20", speaker: "Agent", text: "Take the elevator opposite bookstore up to the third floor.", translation: "乘书店对面的电梯上三楼。", note: "用 'opposite bookstore' 作为定位标志。" },
    { id: "travel-21", speaker: "Traveler", text: "I appreciate your immense assistance today.", translation: "非常感谢您今天的悉心帮助。", note: "用 'immense assistance' 表达感激。" },
    { id: "travel-22", speaker: "Agent", text: "You're very welcome. Have a pleasant journey ahead!", translation: "不客气。祝您旅途愉快！", note: "标准客服祝福语。" },
    { id: "travel-23", speaker: "Traveler", text: "Thanks again. Goodbye!", translation: "再次谢谢您。再见！", note: "礼貌道别。" },
    { id: "travel-24", speaker: "Agent", text: "Safe travels!", translation: "一路平安！", note: "祝愿出行安全。" },
    { id: "travel-25", speaker: "Traveler", text: "By the way, is free Wi-Fi available throughout the terminal?", translation: "顺便问一下，整个航站楼都有免费Wi-Fi吗？", note: "询问机场网络服务。" },
    { id: "travel-26", speaker: "Agent", text: "Yes, connect to 'AirportFreeWiFi' and accept terms in browser.", translation: "有的，连接 'AirportFreeWiFi' 并在浏览器中接受条款即可。", note: "指示联网步骤。" },
    { id: "travel-27", speaker: "Traveler", text: "That's very convenient for checking emails.", translation: "这查收邮件可太方便了。", note: "表达便利感。" },
    { id: "travel-28", speaker: "Agent", text: "Indeed. Enjoy your stay in London.", translation: "确实如此。祝你在伦敦过得愉快。", note: "送上目的地祝福。" },
    { id: "travel-29", speaker: "Traveler", text: "Will do. Have a great shift!", translation: "会的。祝你值班愉快！", note: "回以良好祝愿。" },
    { id: "travel-30", speaker: "Agent", text: "Thank you, goodbye.", translation: "谢谢你，再见。", note: "客气回应。" },
    { id: "travel-31", speaker: "Traveler", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "travel-32", speaker: "Agent", text: "Have a wonderful flight.", translation: "祝你飞行愉快。", note: "再次祝福。" },
    { id: "travel-33", speaker: "Traveler", text: "Cheers!", translation: "谢谢！", note: "轻松致谢。" },
    { id: "travel-34", speaker: "Agent", text: "Boarding soon!", translation: "马上就要登机啦！", note: "温馨提醒。" },
    { id: "travel-35", speaker: "Traveler", text: "Heading there now.", translation: "我这就过去。", note: "行动回应。" },
    { id: "travel-36", speaker: "Traveler", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "travel-37", speaker: "Traveler", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "travel-38", speaker: "Traveler", text: "Goodbye.", translation: "再见。", note: "挥手。" },
    { id: "travel-39", speaker: "Traveler", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "travel-40", speaker: "Traveler", text: "Take care.", translation: "保重。", note: "回应。" },
  ],
  business: [
    { id: "business-1", speaker: "Sam", text: "Good morning team, let's kick off our weekly sync meeting.", translation: "大家早上好，我们开始每周的同步会议吧。", note: "用 'kick off' 表示会议正式开始。" },
    { id: "business-2", speaker: "Lee", text: "Morning Sam. I have prepared the quarterly marketing performance slides.", translation: "早上好萨姆。我已经准备好了季度市场表现幻灯片。", note: "用 'quarterly marketing performance' 介绍季度营销汇报。" },
    { id: "business-3", speaker: "Sam", text: "Excellent. Let's start by reviewing key traffic milestones achieved.", translation: "太好了。我们先回顾一下达成的主要流量里程碑。", note: "用 'traffic milestones' 表示流量里程碑。" },
    { id: "business-4", speaker: "Lee", text: "Organic traffic increased by 25% following our SEO campaign overhaul.", translation: "在我们的SEO活动改版后，自然流量增长了25%。", note: "用 'Organic traffic' 表示自然流量。" },
    { id: "business-5", speaker: "Sam", text: "That's a remarkable achievement for such a short timeframe.", translation: "在这么短的时间内取得这个成绩相当了不起。", note: "用 'remarkable achievement' 表达高度肯定。" },
    { id: "business-6", speaker: "Lee", text: "Credit goes to the content strategy team for robust keyword targeting.", translation: "这要归功于内容策略团队精准的关键词定位。", note: "用 'Credit goes to' 表达对团队的认可。" },
    { id: "business-7", speaker: "Sam", text: "Agreed. What about conversion rates on our landing pages?", translation: "完全同意。我们落地页的转化率情况如何？", note: "用 'conversion rates' 询问转化率指标。" },
    { id: "business-8", speaker: "Lee", text: "Conversion rose from 3.2% to 4.8% after streamlining checkout forms.", translation: "在精简结账表单后，转化率从3.2%上升到了4.8%。", note: "用 'streamlining checkout forms' 表达优化结账流程。" },
    { id: "business-9", speaker: "Sam", text: "Reducing friction in user experience always pays off.", translation: "减少用户体验中的阻力总是奏效的。", note: "用 'Reducing friction' 表示减少操作摩擦。" },
    { id: "business-10", speaker: "Lee", text: "Exactly. Next, we need to discuss budget allocation for next quarter.", translation: "确实如此。接下来，我们需要讨论下季度的预算分配。", note: "用 'budget allocation' 引出预算话题。" },
    { id: "business-11", speaker: "Sam", text: "Do we need additional funding for social media advertising?", translation: "我们在社交媒体广告上需要追加资金吗？", note: "用 'additional funding' 询问资金追加。" },
    { id: "business-12", speaker: "Lee", text: "A modest 15% increase would help us scale high-converting campaigns.", translation: "适度增加15%将帮助我们扩大高转化广告活动的规模。", note: "用 'scale high-converting campaigns' 表达扩大营销规模。" },
    { id: "business-13", speaker: "Sam", text: "I support that proposal, provided we track ROI closely.", translation: "我支持这个提案，前提是我们密切追踪投资回报率。", note: "用 'provided we track ROI' 设定前提条件。" },
    { id: "business-14", speaker: "Lee", text: "We have automated dashboard reporting set up to monitor ROI daily.", translation: "我们已经设置了自动化看板来每日监控投资回报率。", note: "用 'automated dashboard' 表示自动化数据看板。" },
    { id: "business-15", speaker: "Sam", text: "Fantastic. Let's make sure cross-departmental alignment is maintained.", translation: "太棒了。让我们确保跨部门协作保持高度一致。", note: "用 'cross-departmental alignment' 强调部门协同。" },
    { id: "business-16", speaker: "Lee", text: "Product and sales teams are already looped into the new timeline.", translation: "产品团队和销售团队已经同步到了最新的时间线中。", note: "用 'looped into' 表示纳入沟通环。" },
    { id: "business-17", speaker: "Sam", text: "Wonderful. Are there any risks or bottlenecks we should anticipate?", translation: "很好。有什么我们需要提前预防的风险或瓶颈吗？", note: "用 'bottlenecks' 询问潜在瓶颈。" },
    { id: "business-18", speaker: "Lee", text: "Server capacity during flash sales might require minor scaling.", translation: "闪购期间的服务器承载力可能需要适当扩容。", note: "用 'Server capacity' 讨论服务器压力。" },
    { id: "business-19", speaker: "Sam", text: "I'll coordinate with the engineering lead right after this meeting.", translation: "会后我立刻跟工程负责人协调这件事。", note: "用 'coordinate with' 表示安排协调。" },
    { id: "business-20", speaker: "Lee", text: "Appreciate your prompt action on infrastructure preparedness.", translation: "感谢您对基础设施准备工作的迅速响应。", note: "用 'prompt action' 赞赏行动迅速。" },
    { id: "business-21", speaker: "Sam", text: "Any other agenda items before we wrap up today's sync?", translation: "在我们结束今天的同步会之前，还有其他议程吗？", note: "用 'wrap up' 表示会议收尾。" },
    { id: "business-22", speaker: "Lee", text: "Just a reminder that client feedback surveys are due this Friday.", translation: "只需提醒大家，客户反馈调查问卷本周五截止。", note: "用 'due this Friday' 强调截止日期。" },
    { id: "business-23", speaker: "Sam", text: "Got it. I'll email a reminder to all stakeholders today.", translation: "明白了。我今天会发邮件提醒所有利益相关者。", note: "用 'stakeholders' 表示相关负责人。" },
    { id: "business-24", speaker: "Lee", text: "That covers all points from my end.", translation: "我这边要汇报的就是这些。", note: "总结汇报完毕。" },
    { id: "business-25", speaker: "Sam", text: "Thank you everyone for the productive discussion. Meeting adjourned.", translation: "谢谢大家富有成效的讨论。会议到此结束。", note: "标准散会用语 'Meeting adjourned'。" },
    { id: "business-26", speaker: "Lee", text: "Thanks Sam, have a great rest of the week.", translation: "谢谢萨姆，祝大家一周剩余时间工作愉快。", note: "同事道别。" },
    { id: "business-27", speaker: "Sam", text: "You too. Goodbye!", translation: "你也是。再见！", note: "回应道别。" },
    { id: "business-28", speaker: "Lee", text: "Goodbye.", translation: "再见。", note: "告别。" },
    { id: "business-29", speaker: "Sam", text: "Let's catch up on Slack later.", translation: "稍后我们在Slack上同步进展。", note: "线上协同。" },
    { id: "business-30", speaker: "Lee", text: "Sounds good.", translation: "好的。", note: "赞同。" },
    { id: "business-31", speaker: "Sam", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "business-32", speaker: "Lee", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "business-33", speaker: "Sam", text: "Great execution today.", translation: "今天的执行很棒。", note: "赞赏。" },
    { id: "business-34", speaker: "Lee", text: "Thank you.", translation: "谢谢。", note: "接受。" },
    { id: "business-35", speaker: "Sam", text: "Keep up the momentum.", translation: "继续保持势头。", note: "鼓励。" },
    { id: "business-36", speaker: "Lee", text: "Will do.", translation: "没问题。", note: "答应。" },
    { id: "business-37", speaker: "Sam", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "business-38", speaker: "Lee", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "business-39", speaker: "Sam", text: "Bye!", translation: "拜！", note: "简短道别。" },
    { id: "business-40", speaker: "Lee", text: "Bye!", translation: "拜！", note: "最终告别。" },
  ],
  housing: [
    { id: "housing-1", speaker: "Tenant", text: "Hi, I'm calling about the apartment listing on Main Street.", translation: "您好，我是来咨询主街那套公寓房源的。", note: "用 'apartment listing' 询问公寓房源。" },
    { id: "housing-2", speaker: "Landlord", text: "Hello! Yes, the two-bedroom unit is still available. Would you like to schedule a viewing?", translation: "您好！是的，那套两居室还在。您想预约看房吗？", note: "用 'schedule a viewing' 表示预约看房。" },
    { id: "housing-3", speaker: "Tenant", text: "That would be great. Are you available this Saturday afternoon?", translation: "太好了。您这周六下午有空吗？", note: "用 'Saturday afternoon' 约定周末时间。" },
    { id: "housing-4", speaker: "Landlord", text: "Saturday at 2 PM works perfectly for me. What is your monthly budget?", translation: "周六下午两点对我完全合适。您的每月预算是多少？", note: "用 'monthly budget' 询问月租预算。" },
    { id: "housing-5", speaker: "Tenant", text: "My budget is around eighteen hundred dollars including utilities.", translation: "我的预算在1800美元左右，包含水电费。", note: "用 'including utilities' 说明包含公用事业费。" },
    { id: "housing-6", speaker: "Landlord", text: "Rent is seventeen fifty, and water is included. Electricity is separate.", translation: "房租是1750，水费已含，电费另计。", note: "用 'Electricity is separate' 区分电费。" },
    { id: "housing-7", speaker: "Tenant", text: "That sounds reasonable. Is street parking available?", translation: "听起来很合理。路边可以停车吗？", note: "用 'street parking' 询问路边停车。" },
    { id: "housing-8", speaker: "Landlord", text: "Yes, and we also have assigned garage parking for an extra fee.", translation: "可以的，另外我们有指定车库车位，需额外付费。", note: "用 'assigned garage parking' 介绍车库。" },
    { id: "housing-9", speaker: "Tenant", text: "Good to know. I'll see you on Saturday at two then.", translation: "好的，那我周六两点见。", note: "确认看房时间。" },
    { id: "housing-10", speaker: "Landlord", text: "Looking forward to showing you the apartment. Have a nice day!", translation: "期待带您看房。祝您有美好的一天！", note: "客气道别。" },
    { id: "housing-11", speaker: "Tenant", text: "Thanks, see you then.", translation: "谢谢，回头见。", note: "礼貌回应。" },
    { id: "housing-12", speaker: "Landlord", text: "See you Saturday.", translation: "周六见。", note: "告别。" },
    { id: "housing-13", speaker: "Tenant", text: "By the way, are pets allowed in the building?", translation: "顺便问一下，大楼允许养宠物吗？", note: "询问宠物政策。" },
    { id: "housing-14", speaker: "Landlord", text: "Yes, cats and small dogs are welcome with a small deposit.", translation: "可以的，欢迎猫咪和小狗，只需交少许押金。", note: "解释宠物规定。" },
    { id: "housing-15", speaker: "Tenant", text: "That's fantastic news for my cat.", translation: "这对我的猫来说是个好消息。", note: "表达欣喜。" },
    { id: "housing-16", speaker: "Landlord", text: "Glad to hear that.", translation: "很高兴听到这个。", note: "回应。" },
    { id: "housing-17", speaker: "Tenant", text: "Is the lease term for twelve months?", translation: "租期是12个月吗？", note: "确认租约长度。" },
    { id: "housing-18", speaker: "Landlord", text: "Standard lease is one year, with option to renew.", translation: "标准租期是一年，到期可续约。", note: "说明租约。" },
    { id: "housing-19", speaker: "Tenant", text: "Perfect, that suits my plan.", translation: "完美，符合我的计划。", note: "表示满意。" },
    { id: "housing-20", speaker: "Landlord", text: "Great, see you Saturday.", translation: "太好了，周六见。", note: "敲定。" },
    { id: "housing-21", speaker: "Tenant", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "housing-22", speaker: "Landlord", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "housing-23", speaker: "Tenant", text: "Thanks again.", translation: "再次谢谢。", note: "致谢。" },
    { id: "housing-24", speaker: "Landlord", text: "My pleasure.", translation: "不客气。", note: "客套。" },
    { id: "housing-25", speaker: "Tenant", text: "Have a good one.", translation: "祝一切顺利。", note: "问候。" },
    { id: "housing-26", speaker: "Landlord", text: "You too.", translation: "你也是。", note: "回礼。" },
    { id: "housing-27", speaker: "Tenant", text: "Bye.", translation: "拜。", note: "简短道别。" },
    { id: "housing-28", speaker: "Landlord", text: "Bye.", translation: "拜。", note: "回应。" },
    { id: "housing-29", speaker: "Tenant", text: "See you soon.", translation: "回头见。", note: "道别。" },
    { id: "housing-30", speaker: "Landlord", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "housing-31", speaker: "Tenant", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "housing-32", speaker: "Landlord", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "housing-33", speaker: "Tenant", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "housing-34", speaker: "Landlord", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "housing-35", speaker: "Tenant", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "housing-36", speaker: "Landlord", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "housing-37", speaker: "Tenant", text: "Got it.", translation: "明白了。", note: "知晓。" },
    { id: "housing-38", speaker: "Landlord", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "housing-39", speaker: "Tenant", text: "Talk soon.", translation: "回头聊。", note: "道别。" },
    { id: "housing-40", speaker: "Landlord", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
  ],
  medical: [
    { id: "medical-1", speaker: "Patient", text: "Hello, I need to schedule an appointment with a primary care doctor.", translation: "您好，我需要预约一位全科医生看诊。", note: "用 'primary care doctor' 表示全科家庭医生。" },
    { id: "medical-2", speaker: "Receptionist", text: "Certainly. Are you a new patient, and what insurance do you carry?", translation: "当然可以。请问您是新病人吗？持有哪家保险公司的保险？", note: "询问新病人和保险信息。" },
    { id: "medical-3", speaker: "Patient", text: "I'm a new patient, and I have Blue Cross health insurance.", translation: "我是新病人，我有蓝十字健康保险。", note: "说明保险类型。" },
    { id: "medical-4", speaker: "Receptionist", text: "We accept that plan. Are you experiencing any specific symptoms today?", translation: "我们接受该保险。您今天有什么具体的不适症状吗？", note: "询问具体症状。" },
    { id: "medical-5", speaker: "Patient", text: "I've had a persistent cough and mild fever for two days.", translation: "我连续两天咳嗽不止，并伴有轻微发烧。", note: "描述症状。" },
    { id: "medical-6", speaker: "Receptionist", text: "Dr. Smith has an opening tomorrow morning at 10 AM. Does that work?", translation: "史密斯医生明天上午10点有一个号，您看行吗？", note: "提供预约时间。" },
    { id: "medical-7", speaker: "Patient", text: "Yes, ten o'clock tomorrow morning works wonderfully.", translation: "行，明天上午10点非常合适。", note: "确认时间。" },
    { id: "medical-8", speaker: "Receptionist", text: "Please bring your insurance card and photo ID fifteen minutes early.", translation: "请提前十五分钟带上您的保险卡和带照片的身份证件。", note: "提醒携带证件。" },
    { id: "medical-9", speaker: "Patient", text: "Will do. Do I need to fill out any paperwork in advance?", translation: "好的。我需要提前填写什么表格吗？", note: "询问表格。" },
    { id: "medical-10", speaker: "Receptionist", text: "You can complete the intake forms online via our patient portal.", translation: "您可以通过我们的患者门户网站在线填写注册表格。", note: "指导在线填表。" },
    { id: "medical-11", speaker: "Patient", text: "That is very convenient. Thank you.", translation: "这非常方便。谢谢您。", note: "表达谢意。" },
    { id: "medical-12", speaker: "Receptionist", text: "You're welcome. See you tomorrow.", translation: "不客气，明天见。", note: "客套。" },
    { id: "medical-13", speaker: "Patient", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "medical-14", speaker: "Receptionist", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "medical-15", speaker: "Patient", text: "By the way, is parking free at the clinic?", translation: "顺便问一下，诊所停车免费吗？", note: "询问停车。" },
    { id: "medical-16", speaker: "Receptionist", text: "Yes, patient parking is free in the rear lot.", translation: "是的，后面停车场对病人免费开放。", note: "回答停车。" },
    { id: "medical-17", speaker: "Patient", text: "Good to know.", translation: "太好了，知道了。", note: "知晓。" },
    { id: "medical-18", speaker: "Receptionist", text: "Anything else I can help with?", translation: "还有什么我可以帮您的吗？", note: "询问其他。" },
    { id: "medical-19", speaker: "Patient", text: "No, that's all for now.", translation: "没有了，暂时就这些。", note: "回答。" },
    { id: "medical-20", speaker: "Receptionist", text: "Have a speedy recovery.", translation: "祝您早日康复。", note: "祝福。" },
    { id: "medical-21", speaker: "Patient", text: "Thank you.", translation: "谢谢。", note: "道谢。" },
    { id: "medical-22", speaker: "Receptionist", text: "Take care.", translation: "保重。", note: "问候。" },
    { id: "medical-23", speaker: "Patient", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "medical-24", speaker: "Receptionist", text: "Bye.", translation: "拜。", note: "告别。" },
    { id: "medical-25", speaker: "Receptionist", text: "Bye.", translation: "拜。", note: "回应。" },
    { id: "medical-26", speaker: "Doctor", text: "Hello, what brings you in today?", translation: "您好，今天哪里不舒服？", note: "医生问诊。" },
    { id: "medical-27", speaker: "Patient", text: "I have a sore throat and cough.", translation: "我嗓子痛且咳嗽。", note: "回答。" },
    { id: "medical-28", speaker: "Doctor", text: "Let me check your temperature and throat.", translation: "我来帮您测个体温并检查咽喉。", note: "检查。" },
    { id: "medical-29", speaker: "Patient", text: "Sure, go ahead.", translation: "好的，请检查。", note: "配合。" },
    { id: "medical-30", speaker: "Doctor", text: "It looks like a mild upper respiratory infection.", translation: "看起来是轻微的上呼吸道感染。", note: "诊断。" },
    { id: "medical-31", speaker: "Patient", text: "Do I need antibiotics?", translation: "我需要吃抗生素吗？", note: "询问用药。" },
    { id: "medical-32", speaker: "Doctor", text: "No, just rest, hydration, and over-the-counter medicine.", translation: "不需要，多休息、多喝水、吃点非处方药就行。", note: "医嘱。" },
    { id: "medical-33", speaker: "Patient", text: "Understood, thank you doctor.", translation: "明白了，谢谢医生。", note: "道谢。" },
    { id: "medical-34", speaker: "Doctor", text: "Rest well and feel better soon.", translation: "好好休息，早日康复。", note: "祝福。" },
    { id: "medical-35", speaker: "Patient", text: "Thanks, goodbye.", translation: "谢谢，再见。", note: "道别。" },
    { id: "medical-36", speaker: "Doctor", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "medical-37", speaker: "Patient", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "medical-38", speaker: "Doctor", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "medical-39", speaker: "Patient", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "medical-40", speaker: "Doctor", text: "Bye!", translation: "拜！", note: "回应。" },
  ],
  banking: [
    { id: "banking-1", speaker: "Customer", text: "Hello, I would like to open a checking account and a savings account.", translation: "您好，我想开立一个支票账户和一个储蓄账户。", note: "表达开户需求。" },
    { id: "banking-2", speaker: "Banker", text: "Welcome! I'd be happy to help you. Do you have two forms of ID?", translation: "欢迎！我很乐意帮您。请问您有两份身份证明吗？", note: "询问证件。" },
    { id: "banking-3", speaker: "Customer", text: "Yes, I have my passport and my driver's license here.", translation: "有的，我带了护照和驾照。", note: "提供证件。" },
    { id: "banking-4", speaker: "Banker", text: "Perfect. We have a standard account with no monthly fee if you maintain a minimum balance.", translation: "太好了。如果我们标准账户保持最低余额，就没有月费。", note: "介绍账户条款。" },
    { id: "banking-5", speaker: "Customer", text: "What is the minimum balance required to waive the fee?", translation: "免收月费所需的最低余额是多少？", note: "询问最低余额。" },
    { id: "banking-6", speaker: "Banker", text: "You need to keep a daily average balance of fifteen hundred dollars.", translation: "您需要保持每日平均余额1500美元。", note: "回答余额标准。" },
    { id: "banking-7", speaker: "Customer", text: "That sounds manageable. Can I get a debit card today?", translation: "这可以接受。我今天能拿到借记卡吗？", note: "询问借记卡。" },
    { id: "banking-8", speaker: "Banker", text: "I can issue a temporary debit card right now, and the permanent one will arrive by mail.", translation: "我现在可以为您发一张临时借记卡，正式卡会通过邮寄送达。", note: "解释发卡方式。" },
    { id: "banking-9", speaker: "Customer", text: "Wonderful. I'd also like to deposit my initial opening check.", translation: "太好了。我还想存入我的初始开户支票。", note: "办理存款。" },
    { id: "banking-10", speaker: "Banker", text: "Just endorse the back of the check, and I'll process it immediately.", translation: "只需在支票背面签名背书，我马上为您处理。", note: "指导支票背书。" },
    { id: "banking-11", speaker: "Customer", text: "All done. Thank you for your professional guidance.", translation: "弄好了。感谢您的专业指导。", note: "道谢。" },
    { id: "banking-12", speaker: "Banker", text: "You're very welcome. Is there anything else I can set up for you?", translation: "不用客气。还有什么我可以为您设置的吗？", note: "询问其他服务。" },
    { id: "banking-13", speaker: "Customer", text: "Could you also help me activate online mobile banking?", translation: "能帮我开通手机网上银行吗？", note: "开通网银。" },
    { id: "banking-14", speaker: "Banker", text: "Certainly, just download our app and scan this activation QR code.", translation: "当然，下载我们的APP并扫描这个激活二维码即可。", note: "指导网银。" },
    { id: "banking-15", speaker: "Customer", text: "Got it. App is downloaded and logging in now.", translation: "明白了。APP已下载，现在登录中。", note: "操作反馈。" },
    { id: "banking-16", speaker: "Banker", text: "Great! You should receive a verification code via text message shortly.", translation: "太好了！您很快会收到一条短信验证码。", note: "短信验证。" },
    { id: "banking-17", speaker: "Customer", text: "Code received and entered. Account is linked successfully.", translation: "验证码收到并已输入。账户关联成功！", note: "成功关联。" },
    { id: "banking-18", speaker: "Banker", text: "Wonderful! You're all set with your new accounts.", translation: "太棒了！您的新账户一切就绪。", note: "祝贺。" },
    { id: "banking-19", speaker: "Customer", text: "Thank you so much, have a great day.", translation: "非常感谢，祝您有美好的一天。", note: "道谢。" },
    { id: "banking-20", speaker: "Banker", text: "You too! Welcome to our bank.", translation: "你也一样！欢迎来到我们银行。", note: "欢迎。" },
    { id: "banking-21", speaker: "Customer", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "banking-22", speaker: "Banker", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "banking-23", speaker: "Customer", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "banking-24", speaker: "Banker", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "banking-25", speaker: "Customer", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "banking-26", speaker: "Banker", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "banking-27", speaker: "Customer", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "banking-28", speaker: "Banker", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "banking-29", speaker: "Customer", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "banking-30", speaker: "Banker", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "banking-31", speaker: "Customer", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "banking-32", speaker: "Banker", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "banking-33", speaker: "Customer", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "banking-34", speaker: "Banker", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "banking-35", speaker: "Customer", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "banking-36", speaker: "Banker", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "banking-37", speaker: "Customer", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "banking-38", speaker: "Banker", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "banking-39", speaker: "Customer", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "banking-40", speaker: "Banker", text: "Cheers!", translation: "干杯！", note: "回礼。" },
  ],
  shopping: [
    { id: "shopping-1", speaker: "Shopper", text: "Excuse me, where can I find organic vegetables in this aisle?", translation: "打扰一下，请问有机蔬菜在这个过道的哪个位置？", note: "询问商品位置。" },
    { id: "shopping-2", speaker: "Employee", text: "They are located in aisle four, right next to the dairy section.", translation: "它们在第四过道，紧挨着乳制品区。", note: "指明方位。" },
    { id: "shopping-3", speaker: "Shopper", text: "Thank you so much. Also, is this brand of olive oil on sale today?", translation: "非常感谢。另外，这个牌子的橄榄油今天打折吗？", note: "询问促销。" },
    { id: "shopping-4", speaker: "Employee", text: "Yes, it's buy one get one free with your store rewards card.", translation: "是的，凭商店会员卡可以享受买一赠一。", note: "解释优惠。" },
    { id: "shopping-5", speaker: "Shopper", text: "That's a great deal! I'll take two bottles then.", translation: "这太划算了！那我要两瓶。", note: "决定购买。" },
    { id: "shopping-6", speaker: "Employee", text: "Self-checkout registers are open if you only have a few items.", translation: "如果您东西不多，自助结账收银机现在正开放。", note: "指引自助结账。" },
    { id: "shopping-7", speaker: "Shopper", text: "Great, I'll head over there. Can I pay with contactless phone payment?", translation: "太好了，我这就过去。可以用手机无接触支付吗？", note: "询问支付方式。" },
    { id: "shopping-8", speaker: "Employee", text: "Yes, all our registers support Apple Pay and tap-to-pay cards.", translation: "可以的，我们所有的收银机都支持Apple Pay和刷卡感应。", note: "确认支付。" },
    { id: "shopping-9", speaker: "Shopper", text: "Fantastic. Have a wonderful rest of your day.", translation: "太棒了。祝您余下的时间过得愉快。", note: "道谢。" },
    { id: "shopping-10", speaker: "Employee", text: "Thank you! Enjoy your groceries.", translation: "谢谢您！祝您购物愉快。", note: "回应祝福。" },
    { id: "shopping-11", speaker: "Shopper", text: "By the way, do I need to bring my own shopping bags?", translation: "顺便问一下，我需要自带购物袋吗？", note: "询问环保袋。" },
    { id: "shopping-12", speaker: "Employee", text: "We sell paper bags at the register, but bringing reusable bags is encouraged.", translation: "我们在收银台售卖纸袋，不过鼓励自带环保袋。", note: "回答袋子。" },
    { id: "shopping-13", speaker: "Shopper", text: "I have my own bags in the car.", translation: "我车里有自己的袋子。", note: "说明。" },
    { id: "shopping-14", speaker: "Employee", text: "That's wonderful.", translation: "那太好了。", note: "赞许。" },
    { id: "shopping-15", speaker: "Shopper", text: "Thanks for your help.", translation: "谢谢您的帮助。", note: "道谢。" },
    { id: "shopping-16", speaker: "Employee", text: "My pleasure.", translation: "不客气。", note: "客气。" },
    { id: "shopping-17", speaker: "Shopper", text: "Have a good one.", translation: "祝一切顺利。", note: "问候。" },
    { id: "shopping-18", speaker: "Employee", text: "You too.", translation: "你也是。", note: "回礼。" },
    { id: "shopping-19", speaker: "Shopper", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "shopping-20", speaker: "Employee", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "shopping-21", speaker: "Shopper", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "shopping-22", speaker: "Employee", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "shopping-23", speaker: "Shopper", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "shopping-24", speaker: "Employee", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "shopping-25", speaker: "Shopper", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "shopping-26", speaker: "Employee", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "shopping-27", speaker: "Shopper", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "shopping-28", speaker: "Employee", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "shopping-29", speaker: "Shopper", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "shopping-30", speaker: "Employee", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "shopping-31", speaker: "Shopper", text: "Got it.", translation: "明白了。", note: "知晓。" },
    { id: "shopping-32", speaker: "Shopper", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "shopping-33", speaker: "Shopper", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "shopping-34", speaker: "Shopper", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "shopping-35", speaker: "Shopper", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "shopping-36", speaker: "Shopper", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "shopping-37", speaker: "Shopper", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "shopping-38", speaker: "Shopper", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "shopping-39", speaker: "Shopper", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "shopping-40", speaker: "Shopper", text: "Cheers!", translation: "干杯！", note: "回礼。" },
  ],
  transit: [
    { id: "transit-1", speaker: "Commuter", text: "Hello, how do I purchase a reloadable transit card here?", translation: "您好，请问在这里怎么买一张可充值的公交卡？", note: "询问购卡。" },
    { id: "transit-2", speaker: "StationAgent", text: "You can buy a Metro card at this ticket machine using cash or card.", translation: "您可以在这台售票机上用现金或银行卡购买地铁卡。", note: "指示机器购卡。" },
    { id: "transit-3", speaker: "Commuter", text: "Does this card cover both the subway and local buses?", translation: "这张卡既能坐地铁也能坐当地公交吗？", note: "询问适用范围。" },
    { id: "transit-4", speaker: "StationAgent", text: "Yes, it gives you free transfers between buses and subways within two hours.", translation: "是的，两小时内在公交和地铁之间换乘免费。", note: "解释换乘优惠。" },
    { id: "transit-5", speaker: "Commuter", text: "That's very convenient. I'd like to load twenty dollars onto a new card.", translation: "这太方便了。我想给新卡充值20美元。", note: "办理充值。" },
    { id: "transit-6", speaker: "StationAgent", text: "Just select 'New Card', insert your payment, and collect your card from below.", translation: "只需选择‘新卡’，投入付款，然后从下方取卡即可。", note: "指导操作。" },
    { id: "transit-7", speaker: "Commuter", text: "Got it. Which platform do I need for downtown bound trains?", translation: "明白了。去市中心方向的列车在哪个站台？", note: "询问站台。" },
    { id: "transit-8", speaker: "StationAgent", text: "Platform B on the lower level. Trains arrive every six minutes.", translation: "地下一层的B站台。每六分钟一班车。", note: "指示站台与班次。" },
    { id: "transit-9", speaker: "Commuter", text: "Thank you for your clear instructions.", translation: "感谢您的清晰指引。", note: "道谢。" },
    { id: "transit-10", speaker: "StationAgent", text: "Safe travels and have a smooth commute!", translation: "一路平安，通勤顺利！", note: "祝福。" },
    { id: "transit-11", speaker: "Commuter", text: "By the way, is parking free at the station garage?", translation: "顺便问一下，车站车库停车免费吗？", note: "询问停车。" },
    { id: "transit-12", speaker: "StationAgent", text: "Parking is free for transit riders with a valid card validation.", translation: "凭有效刷卡记录，乘客停车是免费的。", note: "回答停车。" },
    { id: "transit-13", speaker: "Commuter", text: "That is awesome.", translation: "这太棒了。", note: "赞叹。" },
    { id: "transit-14", speaker: "StationAgent", text: "Indeed it is.", translation: "确实如此。", note: "回应。" },
    { id: "transit-15", speaker: "Commuter", text: "Thanks again.", translation: "再次感谢。", note: "道谢。" },
    { id: "transit-16", speaker: "StationAgent", text: "You're welcome.", translation: "不客气。", note: "客气。" },
    { id: "transit-17", speaker: "Commuter", text: "Have a great day.", translation: "祝您过得愉快。", note: "祝福。" },
    { id: "transit-18", speaker: "StationAgent", text: "You too.", translation: "你也是。", note: "回礼。" },
    { id: "transit-19", speaker: "Commuter", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "transit-20", speaker: "StationAgent", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "transit-21", speaker: "Commuter", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "transit-22", speaker: "StationAgent", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "transit-23", speaker: "Commuter", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "transit-24", speaker: "StationAgent", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "transit-25", speaker: "Commuter", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "transit-26", speaker: "StationAgent", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "transit-27", speaker: "Commuter", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "transit-28", speaker: "StationAgent", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "transit-29", speaker: "Commuter", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "transit-30", speaker: "StationAgent", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "transit-31", speaker: "Commuter", text: "Got it.", translation: "明白了。", note: "知晓。" },
    { id: "transit-32", speaker: "StationAgent", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "transit-33", speaker: "Commuter", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "transit-34", speaker: "StationAgent", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "transit-35", speaker: "Commuter", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "transit-36", speaker: "StationAgent", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "transit-37", speaker: "Commuter", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "transit-38", speaker: "StationAgent", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "transit-39", speaker: "Commuter", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "transit-40", speaker: "StationAgent", text: "Cheers!", translation: "干杯！", note: "回礼。" },
  ],
  government: [
    { id: "government-1", speaker: "Resident", text: "Hello, I'd like to mail this priority package to California, please.", translation: "您好，我想把这件优先快递寄往加利福尼亚。", note: "表达寄件需求。" },
    { id: "government-2", speaker: "Clerk", text: "Sure thing. Let me place it on the scale to check the postage.", translation: "没问题。我把它放在秤上算一下邮费。", note: "称重算邮费。" },
    { id: "government-3", speaker: "Resident", text: "Will it arrive by this Friday? It contains important documents.", translation: "这周五前能到吗？里面有重要文件。", note: "询问时效。" },
    { id: "government-4", speaker: "Clerk", text: "Priority mail typically takes two to three business days, so it should arrive on Thursday.", translation: "优先快递通常需要2到3个工作日，所以周四应该能到。", note: "承诺时效。" },
    { id: "government-5", speaker: "Resident", text: "That's wonderful. Can I also add tracking and signature confirmation?", translation: "太好了。我还能加挂追踪号和签收确认吗？", note: "增加增值服务。" },
    { id: "government-6", speaker: "Clerk", text: "Of course. Tracking is included, and signature confirmation is three dollars extra.", translation: "当然。已包含追踪，签收确认额外收费3美元。", note: "介绍费用。" },
    { id: "government-7", speaker: "Resident", text: "I'll take the signature confirmation as well for extra security.", translation: "为了更安全，我也加一个签收确认吧。", note: "确认选择。" },
    { id: "government-8", speaker: "Clerk", text: "Total comes to fourteen fifty. You can tap your card on the keypad.", translation: "总计14.50美元。您可以在键盘上刷卡。", note: "结账。" },
    { id: "government-9", speaker: "Resident", text: "Paid. Here is my receipt, thank you for your help.", translation: "已付款。收据在这，谢谢您的帮助。", note: "付款致谢。" },
    { id: "government-10", speaker: "Clerk", text: "Thank you! Here is your tracking label. Have a great day.", translation: "谢谢您！这是您的追踪条形码。祝您有美好的一天。", note: "收尾。" },
    { id: "government-11", speaker: "Resident", text: "By the way, what time do you close on Saturdays?", translation: "顺便问一下，周六你们几点关门？", note: "询问营业时间。" },
    { id: "government-12", speaker: "Clerk", text: "We are open on Saturdays from 9 AM to 2 PM.", translation: "我们周六上午9点到下午2点营业。", note: "回答时间。" },
    { id: "government-13", speaker: "Resident", text: "That is very helpful to know.", translation: "这对我太有用了。", note: "赞许。" },
    { id: "government-14", speaker: "Clerk", text: "Glad to be of assistance.", translation: "很高兴能帮到您。", note: "客气。" },
    { id: "government-15", speaker: "Resident", text: "Thanks again.", translation: "再次感谢。", note: "道谢。" },
    { id: "government-16", speaker: "Clerk", text: "You're welcome.", translation: "不客气。", note: "客气。" },
    { id: "government-17", speaker: "Resident", text: "Have a good one.", translation: "祝一切顺利。", note: "问候。" },
    { id: "government-18", speaker: "Clerk", text: "You too.", translation: "你也是。", note: "回礼。" },
    { id: "government-19", speaker: "Resident", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "government-20", speaker: "Clerk", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "government-21", speaker: "Resident", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "government-22", speaker: "Clerk", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "government-23", speaker: "Resident", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "government-24", speaker: "Clerk", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "government-25", speaker: "Resident", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "government-26", speaker: "Clerk", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "government-27", speaker: "Resident", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "government-28", speaker: "Clerk", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "government-29", speaker: "Resident", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "government-30", speaker: "Clerk", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "government-31", speaker: "Resident", text: "Got it.", translation: "明白了。", note: "知晓。" },
    { id: "government-32", speaker: "Clerk", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "government-33", speaker: "Resident", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "government-34", speaker: "Clerk", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "government-35", speaker: "Resident", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "government-36", speaker: "Clerk", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "government-37", speaker: "Resident", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "government-38", speaker: "Clerk", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "government-39", speaker: "Resident", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "government-40", speaker: "Clerk", text: "Cheers!", translation: "干杯！", note: "回礼。" },
  ],
  school: [
    { id: "school-1", speaker: "Parent", text: "Hello, I'd like to discuss my child's academic progress this semester.", translation: "您好，我想探讨一下我孩子本学期的学业进展。", note: "表达家校沟通需求。" },
    { id: "school-2", speaker: "Teacher", text: "Welcome! I'm glad you scheduled this conference. Your child is doing wonderfully.", translation: "欢迎！很高兴您预约了这次面谈。您的孩子表现非常出色。", note: "老师欢迎。" },
    { id: "school-3", speaker: "Parent", text: "Thank you. Are there any specific subjects we should focus on improving?", translation: "谢谢您。有什么具体科目是我们应该重点提高的吗？", note: "询问提升点。" },
    { id: "school-4", speaker: "Teacher", text: "Reading comprehension is strong, but math problem-solving could use a little extra practice.", translation: "阅读理解很好，但数学应用题解题可以多加练习。", note: "指出建议。" },
    { id: "school-5", speaker: "Parent", text: "I appreciate that feedback. What online resources do you recommend?", translation: "感谢您的反馈。您推荐哪些在线学习资源呢？", note: "征求资源。" },
    { id: "school-6", speaker: "Teacher", text: "We use an interactive math platform at school that students can access at home.", translation: "我们在学校使用一个互动数学平台，学生在家里也可以登录。", note: "推荐平台。" },
    { id: "school-7", speaker: "Parent", text: "Could you email me the login instructions and parent passcode?", translation: "能把登录说明和家长密码发邮件给我吗？", note: "索取账号。" },
    { id: "school-8", speaker: "Teacher", text: "I'll send those details right after our meeting today.", translation: "我会在今天会议结束后立即把这些细节发给您。", note: "承诺发送。" },
    { id: "school-9", speaker: "Parent", text: "Thank you so much for your dedication and support.", translation: "非常感谢您的辛勤付出与支持。", note: "道谢。" },
    { id: "school-10", speaker: "Teacher", text: "It's my pleasure. Partnering with parents makes all the difference.", translation: "这是我的荣幸。与家长紧密合作会带来巨大的改变。", note: "回应。" },
    { id: "school-11", speaker: "Parent", text: "By the way, when is the upcoming spring break?", translation: "顺便问一下，即将到来的春假是什么时候？", note: "询问假期。" },
    { id: "school-12", speaker: "Teacher", text: "Spring break starts on the second Monday of next month.", translation: "春假从下个月的第二个星期一开始。", note: "回答假期。" },
    { id: "school-13", speaker: "Parent", text: "Thank you for the reminder.", translation: "谢谢您的提醒。", note: "道谢。" },
    { id: "school-14", speaker: "Teacher", text: "You're welcome.", translation: "不客气。", note: "客气。" },
    { id: "school-15", speaker: "Parent", text: "Have a wonderful week.", translation: "祝您一周愉快。", note: "祝福。" },
    { id: "school-16", speaker: "Teacher", text: "You too.", translation: "你也是。", note: "回礼。" },
    { id: "school-17", speaker: "Parent", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "school-18", speaker: "Teacher", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "school-19", speaker: "Parent", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "school-20", speaker: "Teacher", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "school-21", speaker: "Parent", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "school-22", speaker: "Teacher", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "school-23", speaker: "Parent", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "school-24", speaker: "Teacher", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "school-25", speaker: "Parent", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "school-26", speaker: "Teacher", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "school-27", speaker: "Parent", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "school-28", speaker: "Teacher", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "school-29", speaker: "Parent", text: "Got it.", translation: "明白了。", note: "知晓。" },
    { id: "school-30", speaker: "Teacher", text: "Great.", translation: "太好了。", note: "确认。" },
    { id: "school-31", speaker: "Parent", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "school-32", speaker: "Teacher", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "school-33", speaker: "Parent", text: "Could you also tell me about after-school activities?", translation: "您还可以告诉我课后活动吗？", note: "询问课外活动。" },
    { id: "school-34", speaker: "Teacher", text: "We offer several clubs, and I can send you the schedule.", translation: "我们提供几个社团，我可以把活动安排发给您。", note: "介绍课后活动。" },
    { id: "school-35", speaker: "Parent", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "school-36", speaker: "Parent", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "school-37", speaker: "Parent", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "school-38", speaker: "Parent", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "school-39", speaker: "Parent", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "school-40", speaker: "Parent", text: "Cheers!", translation: "干杯！", note: "回礼。" },
  ],
};

export function getSceneLabel(scene: string) { return SCENES.find((item) => item.key === scene)?.title ?? "日常问候"; }
export function getLevelLabel(level: LevelKey) { return LEVELS.find((item) => item.key === level)?.title ?? "初级"; }
export function getSceneLines(scene: SceneKey) { return SCENE_CONTENT[scene]; }
export function getPracticeDialogue(scene: SceneKey) { return SCENE_CONTENT[scene].slice(0, 10); }
export const PRACTICE_DIALOGUE = getPracticeDialogue("greetings");
export const LISTENING_LINES = SCENE_CONTENT.greetings;
